### ISSUE TITLE
Add text field to Open File dialogue to allow users to enter a path directly

### ISSUE THREAD

**Issue by vlasky** [Jacalz/wormhole-gui#28] opened 2021-11-05 01:21 UTC
In a native open file dialogue, in addition to point & click, you have the ability to type/paste a folder directly into a text box. When you press enter or click the "select folder" button, the folder pane lists the contents of that folder.

Often you are copying a path from an Windows explorer window or a shell/terminal/command prompt and this provides a much faster workflow.

It would be awesome to have this in wormhole-gui.

**Comment by Jacalz** [comment] 2021-11-05 07:34
Thanks for opening this feature request. I think this happens to be a duplicate of https://github.com/fyne-io/fyne/issues/1098 in the Fyne toolkit. We are currently aiming for it to be in the next Fyne release, v2.2.0 early next year. I suspect it will be in wormhole-gui somewhere around then. :)

**Closed** 2021-11-05 07:34 UTC
Labels: enhancement, upstream-issue
