### ISSUE TITLE
program is starting but gui doesnt consistently show up

### ISSUE THREAD

**Issue by katchy3132** [Jacalz/wormhole-gui#22] opened 2021-09-05 16:34 UTC
### Description:
#21  seems to be fixed - program is starting but gui doesnt consistently show up it just hangs in the background.

### Steps to Reproduce:
I tried pausing kaspersky and malwarebytes but I didn't see a difference. 
It did start with the GUI a couple times but I'm not sure what was different. 

### Screenshots:
notice I can't switch to the window in Process Explorer :

![image](https://user-images.githubusercontent.com/3707138/132134061-b7499976-9d41-42f1-92b2-1c8919649ca4.png)

### Device (please complete the following information):
 - **OS:**  windows 10
 - **Version:**  19043.1165
 - **Go version:** 
 - **Wormhole-gui version:** 2.3.1

**Comment by Jacalz** [comment] 2021-09-05 17:28
Thanks for filing the issue. I know that there have been errors in the past with old graphics cards/drivers not supporting a new enough version of OpenGL. Would you mind sharing what CPU and GPU model your system contains? I should be able to spin up a debug build tomorrow for extracting more information about why it doesn't start.

**Comment by katchy3132** [comment] 2021-09-05 18:14
Ryzen 5 2600X 
Nvidia GeForce GT 710

**Comment by Jacalz** [comment] 2021-09-05 18:22
Thanks for confirming. On first glance it doesn't look likely to be an issue with OpenGL support. I'll spin up the debug binary tomorrow.

**Comment by Jacalz** [comment] 2021-09-06 19:30
Sorry. It’s been a busy day. Will have the binary ready as soon as I can.

**Comment by Jacalz** [comment] 2021-09-11 18:08
Again, sorry that this is taking time. Have been and am quite busy and have not been at the workstation (with the cross-compiling set up).

**Comment by Jacalz** [comment] 2021-09-16 17:12
I have decided not to spin up a debug build until I have found the reason for https://github.com/Jacalz/wormhole-gui/issues/21.

**Comment by Jacalz** [comment] 2021-09-16 18:18
I'd recommend trying out the binaries on the new v2.3.1 release. I have also attached a debug build here just in case:
[wormhole-gui-v2.3.1-debug.zip](https://github.com/Jacalz/wormhole-gui/files/7180094/wormhole-gui-v2.3.1-debug.zip)

**Comment by katchy3132** [comment] 2021-09-16 19:47
The window wasnt starting on the regular release, so the first time I started the debug build I got the following error with the window displaying correctly  :
```
2021/09/16 22:42:46 Fyne error:  Preferences load error:
2021/09/16 22:42:46   Cause: EOF
2021/09/16 22:42:46   At: /go/pkg/mod/fyne.io/fyne/v2@v2.0.4/app/preferences.go:63
```
the second time there was no debugging text but also no window. 
since then I get this error but no window.

**Comment by Jacalz** [comment] 2021-09-16 19:55
Thanks for the report. I'll look into it and possibly get back with more questions. Looks like it might be an upstream issue in Fyne.

**Comment by Jacalz** [comment] 2021-10-29 20:25
I’m sorry but I don’t quite know how to diagnose this. Are you sure that you are not getting any other messages when using the above debug binaries?

The only idea I have for diagnosing this would be to if you could try and remove the preferences files for wormhole-gui. They should be in something like AppData/Roaming/Fyne/wormhole-gui or similar.

**Comment by Jacalz** [comment] 2021-11-15 16:26
Ping @katchy3132 per the above comment.

**Comment by katchy3132** [comment] 2021-11-16 16:05
hi - I tried this again and was getting the error I had before , then I removed the prefs file you described, and now it seems to be working consistently without the error message. thanks!

**Comment by Jacalz** [comment] 2021-11-16 16:20
Great. Thanks for confirming.

**Comment by katchy3132** [comment] 2021-11-16 16:26
FYI I just replaced the debug binaries with the regular ones and Kaspersky is flagging it https://www.virustotal.com/gui/file/07d58ec83fb74fdf160e3d23241e12854a02d5e31977551e4db75a488b055eb9

**Comment by katchy3132** [comment] 2021-11-16 16:51
I may have spoken too soon - it's hanging again. but I have more info:
I excluded and paused Kaspersky to test this again. 

I don't know what happens but if I clear out the Fyne prefs file it starts normally and closes normally. 
on the second start it seems to zero out the prefs file which causes the GUI not to open and the program to hang in the background. 

killing the process and deleting the prefs resets it back to step 1. 

it was not happening when I was using the debug build before. now it happens with both.

**Comment by Jacalz** [comment] 2021-11-16 17:42
Thanks. Then we have something to go on. Sounds like there is something wrong with the preferences code.

**Comment by Jacalz** [comment] 2021-11-16 18:51
> FYI I just replaced the debug binaries with the regular ones and Kaspersky is flagging it https://www.virustotal.com/gui/file/07d58ec83fb74fdf160e3d23241e12854a02d5e31977551e4db75a488b055eb9

I don't think there's anything to do about that. Bad virus software will always be bad virus software with many false positives.

**Comment by smaragdus** [comment] 2021-12-06 20:57
Both version [2.3.1](https://github.com/Jacalz/wormhole-gui/releases/tag/v2.3.1) and version [2.3.1-debug](https://github.com/Jacalz/wormhole-gui/files/7180094/wormhole-gui-v2.3.1-debug.zip) do not open, the process starts but it immediately closes, screen:

![wormhole-gui 2 3 1 - 2021-12-06 - 001](https://user-images.githubusercontent.com/9025757/144921249-ac0b2b68-e8d7-48bf-a036-d9aa96c2503b.png)

This happens on Windows 8 x64. Perhaps my OS is not supported?

**Comment by Jacalz** [comment] 2021-12-07 06:07
Do you not get any output into the terminal using the debug binaries?

Windows 8 should be supported, I think. I don't personally know anyone that runs Windows 8 so I haven't tested it before though.

I'm sorry that I haven't been able to do anything about this yet. There is a lot to do at the university and I just have limited access to a Windows 10 computer since I switched to daily-driving Linux on my laptop.

**Comment by smaragdus** [comment] 2021-12-07 23:55
@Jacalz 

> Do you not get any output into the terminal using the debug binaries?

No.

I suppose that without access to Windows 8 machine it would be close to impossible to be able to reproduce and investigate the problem. Perhaps if there was an option to run the program in portable mode (the configuration file- preferences.json, saved in program folder, not in AppData) it would be easier to investigate the issue as the configuration would be isolated and one could try to test different versions with different settings.

**Comment by Jacalz** [comment] 2021-12-08 08:50
Hmm, interesting idea but I'm not sure it should be necessary with a portable version. I'll have to get my Windows 10 machine up and running to see if I can replicate there. If it is possible, this should be much easier to fix.

Just as a double-check, @smaragdusm, do you think that you could try the steps mentioned in https://github.com/Jacalz/wormhole-gui/issues/22#issuecomment-955027846? If that's the case, this might be an issue with how the directory structure is generated in Fyne.

**Comment by Jacalz** [comment] 2021-12-08 17:57
I just checked on my Windows 10 computer and I can't replicate this. I even tried to remove the preferences folder and it is being created without any issues.

@smaragdus Could you also confirm what CPU and GPU hardware you have as well as any installed virus software?

**Comment by smaragdus** [comment] 2021-12-09 22:04
@Jacalz 

Short hardware information:

===================================================================================

Computer:      TOSHIBA QOSMIO X870
CPU:           Intel Core i7-3630QM (Ivy Bridge-MB SV, E1)
               2400 MHz (24.00x100.0) @ 3195 MHz (32.00x99.8)
Motherboard:   TOSHIBA Portable PC
Chipset:       Intel HM76 (Panther Point)
Memory:        16384 MBytes @ 798 MHz, 11-11-11-28
               - 4096 MB PC12800 DDR3 SDRAM - Samsung M471B5273CH0-CK0
               - 4096 MB PC12800 DDR3 SDRAM - Samsung M471B5273CH0-CK0
               - 4096 MB PC12800 DDR3 SDRAM - Samsung M471B5273CH0-CK0
               - 4096 MB PC12800 DDR3 SDRAM - Samsung M471B5273CH0-CK0
Graphics:      NVIDIA GeForce GTX 670M [Toshiba]
Drive:         TOSHIBA MQ01ABD100, 976.8 GB, Serial ATA 3Gb/s @ 3Gb/s
Drive:         HGST HTS541010A9E680, 976.8 GB, Serial ATA 3Gb/s @ 3Gb/s
Drive:         TSSTcorp BDDVDW SN-506AB, BD-RE
Sound:         Intel Panther Point PCH - High Definition Audio Controller [C1]
Sound:         NVIDIA GF114 - High Definition Audio Controller
Network:       Qualcomm/Atheros AR8161/8165 PCI-E Gigabit Ethernet Controller
Network:       Intel Centrino Wireless-N 2230 BGN 2x2 HMC WiFi/Bluetooth Adapter
OS:            Microsoft Windows 8  (x64) Build 9200

===================================================================================

If this not enough I may provide more detailed hardware information.

About the anto-virus, I am sure it is not causing the problem as I disabled it when I was trying to run your program, but it did not help. Anyway, I have an old free version of [360 Total Security](https://www.softpedia.com/get/Antivirus/360-Total-Security.shtml) which I keep only for one reason- to prevent programs to add items to Windows shell so I won't need to manually edit Windows registry later to remove unwanted context menu items,

I doubt whether it is worth the effort to investigate this. Sooner or later I will have to switch to Linux (most likely Mint or Manjaro) because I won't go any further than Windows 8.

**Comment by Jacalz** [comment] 2021-12-10 09:49
Thanks for the information. Your system specs, most notably the GPU, seems to be all up to the task. My best bet would be that it is the anti virus not letting the application start, but if it doesn't work with it disabled either, then I have no idea. I'm sorry.

**Comment by smaragdus** [comment] 2021-12-12 00:21
@Jacalz 

I appreciate your helpfulness. What I can do more is to install Windows 8 on a virtual machine and then try to run [wormhole-gui](https://github.com/Jacalz/wormhole-gui). My guess is that this problem is specific to my system and it is hard to reproduce.

**Comment by Jacalz** [comment] 2021-12-12 18:51
You're welcome. I am happy to help if I can. These kind of issues are far from ideal.

I might have an idea to test, when I save some time in the week to do so. The loading of the preferences on startup currently triggers the values to be saved as well. Will see if I can fix that and if that might cause some sort of corruption by reading and writing to the same file at the same time.

I'll also see if I can spin up some new debug binaries running the latest code in the main branch, that will become the 3.0.0 release some time early next year. A lot has changed, especially with using Fyne 2.1.2 over 2.0.3, so we might see something different hopefully (I doubt it, but it doesn't hurt to try).

**Comment by Jacalz** [comment] 2021-12-14 18:36
I have now pushed https://github.com/Jacalz/wormhole-gui/commit/244967f4199d9d0a76150f04bbfca00d75dc2f9c which hopefully makes things better at least. It may or may not solve the issues, I have no idea honestly. However, it should make things a lot better either way :)

Here is a debug build running on the development version of v3.0.0. It should feature a lot of changes over the old debug build, so hopefully something can help out there. Feel free to test and see if it makes anything better for you :)
[wormhole-gui-v3.0.0dev-debug.zip](https://github.com/Jacalz/wormhole-gui/files/7713992/wormhole-gui-v3.0.0dev-debug.zip)

**Comment by Jacalz** [comment] 2022-01-03 19:45
I have removed the old debug binary and attached a new one with all of the latest changes. I would really appreciate if you two could test it out and see if it solves anything.
[wormhole-gui-v3.0.0-debug2-windows-amd64.zip](https://github.com/Jacalz/wormhole-gui/files/7803744/wormhole-gui-v3.0.0-debug2-windows-amd64.zip)

**Comment by smaragdus** [comment] 2022-01-04 21:38
@Jacalz 

First, Happy New Year!

Second, sorry for the late reply.

Third, when I start the debug executable for a second or less a console window appears but it closes almost immediately as the process is terminated.

Fourth, I am almost sure that the problem is within my system (Windows has been installed 7 or 8 years ago).

Fifth, I cannot imagine what else you can do for debugging. I hope you have not wasted too much time. I highly appreciate your good will and the efforts you have put into trying to investigate the problem.

Best regards!

**Comment by Jacalz** [comment] 2022-01-05 07:11
Happy new year! 💥
Thanks for the detailed answer. I will close this issue then. I’ll reopen in the future if I suddenly can replicate or more users show that they have the same problem.

No worries. I haven’t wasted any time on improving this project. Thanks for all the help :)

**Closed by Jacalz** 2022-01-05 07:11 UTC
Labels: bug, help wanted
